[package]
name = "common-meta-raft-store"
version = "0.1.0"
description = "Raft state machine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[dependencies]
common-arrow = {path = "../../arrow"}
common-exception = {path = "../../exception"}
common-io = {path = "../../io"}
common-meta-api = {path = "../api"}
common-meta-sled-store = {path = "../sled-store"}
common-meta-types = {path = "../types"}
common-tracing = {path = "../../tracing"}

anyhow = "1.0.45"
async-raft = { git = "https://github.com/datafuse-extras/async-raft", tag = "v0.6.2-alpha.16" }
async-trait = "0.1"
bytes = "1"
derive_more = "0.99.16"
maplit = "1.0.2"
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
structopt-toml = "0.5.0"

[dev-dependencies]
common-base = {path = "../../base" }
pretty_assertions = "1.0"
tempfile = "3.2.0"
