[package]
name = "bendctl"
version = "0.1.0"
description = "All-in-one tool for setting up, managing with Databend"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lib]
doctest = false
test = false

[[bin]]
name = "bendctl"
path = "src/bin/bendctl.rs"

[features]

[dependencies]
# Workspace dependencies
databend-query = {path = "../query"}
common-base = {path = "../common/base" }
common-datavalues = { path = "../common/datavalues" }
itertools = "0.10.1"
shellwords = "1.1.0"
databend-meta = {path = "../metasrv" }
common-meta-raft-store= {path = "../common/meta/raft-store"}
colored = "2.0.0"
comfy-table = "4.1.1"
dirs = "4.0.0"
clap = "3.0.0-beta.5"
clap_generate = "3.0.0-beta.5"
dyn-clone = "1.0.4"
flate2 = "1.0.22"
handlebars = "4.1.3"
indicatif = "0.16.2"
run_script = "^0.9.0"
rustyline = "9.0.0"
futures = "0.3"
byte-unit = "4.0.13"
num-format = "0.4.0"
fs_extra = "1.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.8"
sysinfo = "0.20.5"
tar = "0.4.37"
thiserror = "1.0.30"
ureq = { version = "2.3.1", features = ["json"] }
nix = "0.22.2"
log = "0.4"
serde_yaml = "0.8.21"
structopt = "0.3"
structopt-toml = "0.5.0"
portpicker = "0.1.1"
reqwest = { version = "0.11", features = ["json", "native-tls", "blocking", "tokio-rustls", "stream"] }
libc = "0.2"
lexical-util = "0.8.1"
async-trait = "0.1"
webbrowser = "0.5.5"
async-std = "1.10.0"
tryhard = "0.4.0"
rayon = "1.5.1"
tokio-util = "0.6.9"
csv = "1.1"

[dev-dependencies]
pretty_assertions = "1.0"
tempfile = "3.2.0"
assert_cmd = "2.0.2"
predicates = "2.0.3"
httpmock = "0.6"

[build-dependencies]
common-building = {path = "../common/building"}