[package]
name = "databend-query"
version = "0.1.0"
description = "A real-time Cloud Distributed Query Engine"
authors = ["Databend Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "databend-query"
path = "src/bin/databend-query.rs"

[[bin]]
name = "databend-benchmark"
path = "src/bin/databend-benchmark.rs"

[features]
default = ["simd"]
simd = ["common-arrow/simd"]

[dependencies]
# Workspace dependencies
common-arrow = { path = "../common/arrow" }
common-base = { path = "../common/base" }
common-cache = { path = "../common/cache" }
common-clickhouse-srv = { path = "../common/clickhouse-srv" }
common-dal = { path = "../common/dal" }
common-datablocks = { path = "../common/datablocks" }
common-datavalues = { path = "../common/datavalues" }
common-exception = { path = "../common/exception" }
common-flight-rpc = { path = "../common/flight-rpc" }
common-functions = { path = "../common/functions" }
common-infallible = { path = "../common/infallible" }
common-io = { path = "../common/io" }
common-management = { path = "../common/management" }
common-mem-allocator = { path = "../common/mem-allocator" }
common-meta-api = { path = "../common/meta/api" }
common-meta-embedded = { path = "../common/meta/embedded" }
common-meta-flight = { path = "../common/meta/flight" }
common-meta-sled-store = { path = "../common/meta/sled-store" }
common-meta-types = { path = "../common/meta/types" }
common-macros = { path = "../common/macros" }
common-metrics = { path = "../common/metrics" }
common-planners = { path = "../common/planners" }
common-streams = { path = "../common/streams" }
common-tracing = { path = "../common/tracing" }

# Github dependencies
clickhouse-rs = { git = "https://github.com/datafuse-extras/clickhouse-rs", rev = "c4743a9" }
msql-srv = { git = "https://github.com/datafuse-extras/msql-srv", rev = "e4c8f3d" }
sqlparser = { git = "https://github.com/datafuse-extras/sqlparser-rs", rev = "599d75a", default-features = false }

# Crates.io dependencies
ahash = "0.7.6"
async-compat = "0.2.1"
async-trait = "0.1"
async-stream = "0.3.2"
poem = { version = "1.0.30", features = ["rustls", "multipart"] }
bumpalo = "3.8.0"
byteorder = "1"
bytes = "1"
cargo-license = "0.4.2"
cargo_metadata = "0.14.1"
chrono = "0.4.0"
chrono-tz = "0.6"
crossbeam = "0.8"
crossbeam-queue = "0.3.2"
ctrlc = { version = "3.1.9", features = ["termination"] }
dyn-clone = "1.0.4"
env_logger = "0.9"
futures = "0.3"
headers = "0.3.4"
hyper = "0.14.14"
indexmap = "1.7.0"
lazy_static = "1.4.0"
log = "0.4"
metrics = "0.17.0"
nom = "7.1.0"
num = "0.4"
num_cpus = "1.0"
octocrab = "0.15"
paste = "^1.0"
prost = "0.9.0"
quantiles = "0.7.1"
rand = "0.8.4"
reqwest = { version = "0.11" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha1 = "0.6.0"
sha2 = "0.9.8"
structopt = "0.3"
structopt-toml = "0.5.0"
threadpool = "1.8.1"
tokio-rustls = "0.23.1"
tokio-stream = { version = "0.1", features = ["net"] }
toml = "0.5.8"
tonic = "0.6.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
walkdir = "2.3.2"

[dependencies.parquet-format-async-temp]
version = "0.2.0"

[dev-dependencies]
criterion = "0.3"
flaky_test = "0.1"
mysql = "21.0.1"
pretty_assertions = "1.0"
reqwest = { version = "0.11", features = ["json", "native-tls"] }
tempfile = "3.2.0"

[build-dependencies]
common-building = { path = "../common/building" }

[[bench]]
name = "bench_main"
harness = false
